#!/command/with-contenv bash
# shellcheck shell=bash

exec \
    s6-setuidgid abc \
    /lsiopy/moonraker-env/bin/python3 \
    /app/moonraker/moonraker/moonraker.py \
    -d /config/printer_data \
    > /dev/null 