#!/command/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 10200" \
        s6-setuidgid abc \
        /lsiopy/klippy-env/bin/python3 \
        /app/klipper/klippy/klippy.py \
        /config/printer_data/config/printer.cfg \
        -a /tmp/klippy_uds \
        -l /config/printer_data/logs/klippy.log 

